# Generated by Django 2.0 on 2018-02-16 10:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=140)),
                ('image', models.ImageField(blank=True, upload_to='service/')),
                ('background', models.ImageField(blank=True, upload_to='service/')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='service/')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('text', ckeditor.fields.RichTextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.Service')),
            ],
            options={
                'verbose_name': 'Imágen del carousel',
                'verbose_name_plural': 'Imagenes del carousel',
            },
        ),
    ]
