# Generated by Django 2.0 on 2018-02-26 07:05

import ckeditor.fields
from django.db import migrations, models
import sorl.thumbnail.fields
import src.services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180225_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.services.models.get_upload_path, verbose_name='Foto de fondo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.services.models.get_upload_path, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=140, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, max_length=140, verbose_name='Slug "SEO"'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=140, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.services.models.get_upload_path, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='name',
            field=models.CharField(blank=True, max_length=144, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
    ]
