# Generated by Django 2.0 on 2018-02-16 10:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('crated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousel',
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='frontend/')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('text', ckeditor.fields.RichTextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('Carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.Carousel')),
                ('call_to_action_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flatpages.FlatPage')),
            ],
            options={
                'verbose_name': 'Imágen del carousel',
                'verbose_name_plural': 'Imagenes del carousel',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('have_icon', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=18, null=True)),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Paginas',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140)),
                ('title', models.CharField(blank=True, max_length=144, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('short_description', ckeditor.fields.RichTextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=140)),
                ('phone', models.CharField(blank=True, max_length=144, null=True)),
                ('email', models.CharField(blank=True, max_length=144, null=True)),
                ('logo', models.ImageField(default='/static/base/img/moby.png', upload_to='site/')),
                ('site_img', models.ImageField(default='/static/base/img/moby.png', upload_to='site/')),
                ('services_img', models.ImageField(default='/static/base/img/moby.png', upload_to='site/')),
                ('products_img', models.ImageField(default='/static/base/img/moby.png', upload_to='site/')),
            ],
            options={
                'verbose_name': 'Informacion del sitio',
                'verbose_name_plural': 'Informacion del sitio',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1444)),
                ('name', models.CharField(blank=True, max_length=1444)),
                ('icon', models.CharField(blank=True, max_length=1444)),
                ('title', models.CharField(blank=True, max_length=1444)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Social_Media', to='base.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
            },
        ),
        migrations.AddField(
            model_name='carousel',
            name='Position',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Position'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='page',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Pages'),
        ),
    ]
