# Generated by Django 2.0 on 2018-02-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='Position',
            new_name='position',
        ),
    ]
