# Generated by Django 2.0 on 2018-02-23 13:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180216_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Perfiles de redes sociales', 'verbose_name_plural': 'Perfiles de redes sociales'},
        ),
        migrations.AlterField(
            model_name='carousel',
            name='crated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='¿Cuando fue creado?'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='name',
            field=models.CharField(blank=True, max_length=144, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='page',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Pages', verbose_name='Página asociada'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='position',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Position', verbose_name='Posición asociada'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='call_to_action_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flatpages.FlatPage', verbose_name='Llamado a acción'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(upload_to='frontend/', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='name',
            field=models.CharField(blank=True, max_length=144, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Testo para mostrar sobre la imágen'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True, verbose_name='¿Cuando fue creado?'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='have_icon',
            field=models.BooleanField(default=False, verbose_name='¿Usa icono?'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='name',
            field=models.CharField(blank=True, max_length=144, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='url',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Dirección url'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, max_length=144, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='site',
            name='email',
            field=models.CharField(blank=True, max_length=144, null=True, verbose_name='Correo electronico principal'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.ImageField(default='/static/base/img/moby.png', upload_to='site/', verbose_name='Logo del sitio'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=140, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='site',
            name='phone',
            field=models.CharField(blank=True, max_length=144, null=True, verbose_name='Número de teléfono principal'),
        ),
        migrations.AlterField(
            model_name='site',
            name='products_img',
            field=models.ImageField(default='/static/base/img/moby.png', upload_to='site/', verbose_name='Imágen para productos'),
        ),
        migrations.AlterField(
            model_name='site',
            name='services_img',
            field=models.ImageField(default='/static/base/img/moby.png', upload_to='site/', verbose_name='Imágen para servicios'),
        ),
        migrations.AlterField(
            model_name='site',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=240, verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_img',
            field=models.ImageField(default='/static/base/img/moby.png', upload_to='site/', verbose_name='Imágen destacada'),
        ),
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(blank=True, max_length=144, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(blank=True, max_length=140, verbose_name='Dirección URL'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(blank=True, choices=[('500px', 'fa-500px'), ('Amazon', 'fa-amazon'), ('Amex', 'fa-cc-amex'), ('Angellist', 'fa-angellist'), ('Behanse', 'fa-behance'), ('Behanse', 'fa-behance'), ('Behanse1', 'fa-behance-square'), ('Bitbucket', 'fa-bitbucket'), ('Bitbucket1', 'fa-bitbucket-square'), ('BitCoin', 'fa-btc'), ('Buysellads', 'fa-buysellads'), ('Codepen', 'fa-codepen '), ('Digg', 'fa-digg'), ('Dinners Clud', 'fa-cc-diners-club'), ('Discover', 'fa-cc-discover'), ('Dribble', 'fa-dribbble'), ('Dropbox', 'fa-dropbox'), ('Facebook', 'fa-facebook'), ('Facebook', 'fa-facebook'), ('Facebook1', 'fa-facebook-square'), ('Facebook2', 'fa-facebook-official'), ('GitHub', 'fa-github'), ('GitHub1', 'fa-github-alt '), ('GitHub2', 'fa-github-square'), ('GitLab', 'fa-gitlab'), ('Google Wallet', 'fa-google-wallet '), ('Google', 'fa-google'), ('Google+', 'fa-google-plus'), ('Google+1', 'fa-google-plus-square'), ('Google+2', 'fa-google-plus-official'), ('Hacker News', 'fa-hacker-news'), ('Instagram', 'fa-instagram'), ('JCB', 'fa-cc-jcb'), ('JsFiddle', 'fa-jsfiddle'), ('LinkedIn', 'fa-linkedin'), ('LinkedIn1', 'fa-linkedin-square'), ('MasterCard', 'fa-cc-mastercard '), ('Medium', 'fa-medium'), ('Meetup', 'fa-meetup'), ('Opencart', 'fa-opencart'), ('Paypal', 'fa-cc-paypal'), ('Paypal', 'fa-paypal'), ('Printerest', 'fa-pinterest'), ('Printerest1', 'fa-pinterest-square'), ('Printerest2', 'fa-pinterest-p'), ('Quora', 'fa-quora'), ('Reddit', 'fa-reddit'), ('Reddit1', 'fa-reddit-square'), ('Reddit2', 'fa-reddit-alien'), ('Skype', 'fa-skype'), ('Slack', 'fa-slack'), ('Slideshare', 'fa-slideshare'), ('Snapchat', 'fa-snapchat'), ('Snapchat1', 'fa-snapchat-square'), ('Snapchat2', 'fa-snapchat-ghost'), ('Soundcloud', 'fa-soundcloud'), ('Spotify', 'fa-spotify'), ('Stack Overflow', 'fa-stack-overflow '), ('Stripe', 'fa-cc-stripe'), ('Telegram', 'fa-telegram'), ('Trello', 'fa-trello'), ('Tripadvisor', 'fa-tripadvisor'), ('Tumblr', 'fa-tumblr'), ('Tumblr1', 'fa-tumblr-square'), ('Twitch', 'fa-twitch'), ('Twitter', 'fa-twitter'), ('Twitter1', 'fa-twitter-square'), ('USB', 'fa-usb'), ('Viacoin', 'fa-viacoin'), ('Vimeo', 'fa-vimeo-square'), ('Vine', 'fa-vine'), ('Visa', 'fa-cc-visa'), ('Weixin', 'fa-weixin'), ('Whatsapp', 'fa-whatsapp'), ('Wikipedia', 'fa-wikipedia-w'), ('Windows', 'fa-windows'), ('Wordpress', 'fa-wordpress'), ('WPBeguinner', 'fa-wpbeginner'), ('WpForms', 'fa-wpforms'), ('Xing Square', 'fa-xing-square'), ('Xing', 'fa-xing'), ('Y Combinator', 'fa-y-combinator'), ('Yahoo', 'fa-yahoo'), ('Yelp', 'fa-yelp'), ('YouTube', 'fa-youtube'), ('YouTube1', 'fa-youtube-square'), ('YouTube2', 'fa-youtube-play')], max_length=1444, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(blank=True, max_length=1444, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(blank=True, max_length=1444, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.CharField(blank=True, max_length=1444, verbose_name='Dirección url'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='name',
            field=models.CharField(blank=True, max_length=144, verbose_name='Nombre'),
        ),
    ]
