# Generated by Django 2.0 on 2018-02-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180223_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(blank=True, choices=[('fa-500px', '500px'), ('fa-amazon', 'Amazon'), ('fa-cc-amex', 'Amex'), ('fa-angellist', 'Angellist'), ('fa-behance', 'Behanse'), ('fa-behance', 'Behanse'), ('fa-behance-square', 'Behanse1'), ('fa-bitbucket', 'Bitbucket'), ('fa-bitbucket-square', 'Bitbucket1'), ('fa-btc', 'BitCoin'), ('fa-buysellads', 'Buysellads'), ('fa-codepen ', 'Codepen'), ('fa-digg', 'Digg'), ('fa-cc-diners-club', 'Dinners Clud'), ('fa-cc-discover', 'Discover'), ('fa-dribbble', 'Dribble'), ('fa-dropbox', 'Dropbox'), ('fa-facebook', 'Facebook'), ('fa-facebook', 'Facebook'), ('fa-facebook-square', 'Facebook1'), ('fa-facebook-official', 'Facebook2'), ('fa-github', 'GitHub'), ('fa-github-alt ', 'GitHub1'), ('fa-github-square', 'GitHub2'), ('fa-gitlab', 'GitLab'), ('fa-google-wallet ', 'Google Wallet'), ('fa-google', 'Google'), ('fa-google-plus', 'Google+'), ('fa-google-plus-square', 'Google+1'), ('fa-google-plus-official', 'Google+2'), ('fa-hacker-news', 'Hacker News'), ('fa-instagram', 'Instagram'), ('fa-cc-jcb', 'JCB'), ('fa-jsfiddle', 'JsFiddle'), ('fa-linkedin', 'LinkedIn'), ('fa-linkedin-square', 'LinkedIn1'), ('fa-cc-mastercard ', 'MasterCard'), ('fa-medium', 'Medium'), ('fa-meetup', 'Meetup'), ('fa-opencart', 'Opencart'), ('fa-cc-paypal', 'Paypal'), ('fa-paypal', 'Paypal'), ('fa-pinterest', 'Printerest'), ('fa-pinterest-square', 'Printerest1'), ('fa-pinterest-p', 'Printerest2'), ('fa-quora', 'Quora'), ('fa-reddit', 'Reddit'), ('fa-reddit-square', 'Reddit1'), ('fa-reddit-alien', 'Reddit2'), ('fa-skype', 'Skype'), ('fa-slack', 'Slack'), ('fa-slideshare', 'Slideshare'), ('fa-snapchat', 'Snapchat'), ('fa-snapchat-square', 'Snapchat1'), ('fa-snapchat-ghost', 'Snapchat2'), ('fa-soundcloud', 'Soundcloud'), ('fa-spotify', 'Spotify'), ('fa-stack-overflow ', 'Stack Overflow'), ('fa-cc-stripe', 'Stripe'), ('fa-telegram', 'Telegram'), ('fa-trello', 'Trello'), ('fa-tripadvisor', 'Tripadvisor'), ('fa-tumblr', 'Tumblr'), ('fa-tumblr-square', 'Tumblr1'), ('fa-twitch', 'Twitch'), ('fa-twitter', 'Twitter'), ('fa-twitter-square', 'Twitter1'), ('fa-usb', 'USB'), ('fa-viacoin', 'Viacoin'), ('fa-vimeo-square', 'Vimeo'), ('fa-vine', 'Vine'), ('fa-cc-visa', 'Visa'), ('fa-weixin', 'Weixin'), ('fa-whatsapp', 'Whatsapp'), ('fa-wikipedia-w', 'Wikipedia'), ('fa-windows', 'Windows'), ('fa-wordpress', 'Wordpress'), ('fa-wpbeginner', 'WPBeguinner'), ('fa-wpforms', 'WpForms'), ('fa-xing-square', 'Xing Square'), ('fa-xing', 'Xing'), ('fa-y-combinator', 'Y Combinator'), ('fa-yahoo', 'Yahoo'), ('fa-yelp', 'Yelp'), ('fa-youtube', 'YouTube'), ('fa-youtube-square', 'YouTube1'), ('fa-youtube-play', 'YouTube2')], max_length=1444, verbose_name='Icono'),
        ),
    ]
