# Generated by Django 2.0 on 2018-02-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180223_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='address',
            field=models.CharField(blank=True, max_length=144, null=True, verbose_name='Dirección principal'),
        ),
        migrations.AddField(
            model_name='site',
            name='address1',
            field=models.CharField(blank=True, max_length=144, null=True, verbose_name='Dirección secundaria'),
        ),
        migrations.AddField(
            model_name='site',
            name='email2',
            field=models.CharField(blank=True, max_length=144, null=True, verbose_name='Correo electronico secundario'),
        ),
        migrations.AddField(
            model_name='site',
            name='phone2',
            field=models.CharField(blank=True, max_length=144, null=True, verbose_name='Número de teléfono secundario'),
        ),
        migrations.AddField(
            model_name='site',
            name='schedule',
            field=models.CharField(blank=True, max_length=144, null=True, verbose_name='Horario de atención'),
        ),
    ]
