# Generated by Django 2.0 on 2018-02-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180223_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='workday',
            field=models.CharField(blank=True, max_length=144, null=True, verbose_name='Días laborales'),
        ),
    ]
