# Generated by Django 2.0 on 2018-02-26 04:08

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_site_workday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='frontend/', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(default='/static/base/img/moby.png', upload_to='site/', verbose_name='Logo del sitio'),
        ),
        migrations.AlterField(
            model_name='site',
            name='products_img',
            field=sorl.thumbnail.fields.ImageField(default='/static/base/img/moby.png', upload_to='site/', verbose_name='Imágen para productos'),
        ),
        migrations.AlterField(
            model_name='site',
            name='services_img',
            field=sorl.thumbnail.fields.ImageField(default='/static/base/img/moby.png', upload_to='site/', verbose_name='Imágen para servicios'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_img',
            field=sorl.thumbnail.fields.ImageField(default='/static/base/img/moby.png', upload_to='site/', verbose_name='Imágen destacada'),
        ),
    ]
