# Generated by Django 2.0 on 2018-02-23 14:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.utils.libs


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', '-updated'], 'verbose_name': 'Articulo del blog', 'verbose_name_plural': 'Articulos del blog'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='¿Está aprovado?'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor del comentario'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Tipo de contenido'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Id de relación'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment', verbose_name='Comentario padre'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='Post asociado'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tiempo creado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor del post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='background',
            field=models.ImageField(blank=True, default='', height_field='background_height_field', null=True, upload_to=src.utils.libs.upload_location, verbose_name='Imágen de fondo', width_field='background_width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='background_height_field',
            field=models.IntegerField(default=0, verbose_name='Anchura imágen de fondo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='background_width_field',
            field=models.IntegerField(default=0, verbose_name='Altura imágen de fondo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='¿Es borrador?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='', height_field='img_height_field', null=True, upload_to=src.utils.libs.upload_location, verbose_name='Imágen de portada', width_field='img_width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_height_field',
            field=models.IntegerField(default=0, verbose_name='Altura Imágen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_width_field',
            field=models.IntegerField(default=0, verbose_name='Anchura Imágen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(auto_now=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo de lectura (Minutos)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Nombre url SEO'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido del post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Titulo del post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima actualización'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
