# Generated by Django 2.0 on 2018-02-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180223_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo de lectura (Minutos)'),
        ),
    ]
