# Generated by Django 2.0 on 2018-02-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180223_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=True, verbose_name='¿Está aprovado?'),
        ),
    ]
