# Generated by Django 2.0 on 2018-02-26 07:05

from django.db import migrations
import sorl.thumbnail.fields
import src.blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180225_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', height_field='background_height_field', null=True, upload_to=src.blog.models.get_upload_path, verbose_name='Imágen de fondo', width_field='background_width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', height_field='img_height_field', null=True, upload_to=src.blog.models.get_upload_path, verbose_name='Imágen de portada', width_field='img_width_field'),
        ),
    ]
