# Generated by Django 2.0 on 2018-02-16 10:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('code', models.CharField(blank=True, max_length=144)),
                ('ref', models.CharField(blank=True, max_length=144)),
                ('line', models.CharField(blank=True, max_length=144)),
                ('sub_line', models.CharField(blank=True, max_length=144)),
                ('category', models.CharField(blank=True, max_length=144)),
                ('provider', models.CharField(blank=True, max_length=144)),
                ('color', models.CharField(blank=True, max_length=144)),
                ('department', models.CharField(blank=True, max_length=144)),
                ('model', models.CharField(blank=True, max_length=144)),
                ('origin', models.CharField(blank=True, max_length=144)),
                ('sales_unit', models.CharField(blank=True, max_length=144)),
                ('stock', models.IntegerField(blank=True, default=0)),
                ('price_1', models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True)),
                ('price_2', models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True)),
                ('price_3', models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True)),
                ('price_4', models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True)),
                ('price_5', models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True)),
                ('item_type', models.CharField(blank=True, max_length=144)),
                ('is_shipping_required', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('imported', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-created_at', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('img', models.ImageField(blank=True, max_length=144, upload_to='')),
                ('background', models.ImageField(blank=True, upload_to='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Category')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('hex_code', models.CharField(blank=True, max_length=9)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('background', models.ImageField(blank=True, upload_to='')),
                ('slug', models.CharField(blank=True, max_length=144)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Linea',
                'verbose_name_plural': 'Lineas',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('background', models.ImageField(blank=True, upload_to='')),
                ('website', models.CharField(blank=True, max_length=144)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='SubLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Line')),
            ],
            options={
                'verbose_name': 'Sub-linea',
                'verbose_name_plural': 'Sub-Linea',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=144)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('background', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Tipo de artículo',
                'verbose_name_plural': 'Tipos de artículos',
            },
        ),
    ]
