# Generated by Django 2.0 on 2018-02-26 04:08

from django.db import migrations
import sorl.thumbnail.fields
import src.ventas.models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, max_length=144, upload_to=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='line',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.ventas.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='provider',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='provider',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='provider',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subline',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='type',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='type',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=''),
        ),
    ]
