# Generated by Django 2.0 on 2018-02-26 07:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields
import src.ventas.models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20180225_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.AlterModelOptions(
            name='subline',
            options={'verbose_name': 'Sublinea', 'verbose_name_plural': 'SubLineas'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=144, verbose_name='Slug "SEO"'),
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='¿Cuando fue cargado?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='slug',
            field=models.CharField(blank=True, max_length=144, verbose_name='Slug "SEO"'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=144, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(blank=True, max_length=144, verbose_name='Código de articulo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='color',
            field=models.CharField(blank=True, max_length=144, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='article',
            name='department',
            field=models.CharField(blank=True, max_length=144, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.ventas.models.get_upload_path, verbose_name='Imagen de articulo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='imported',
            field=models.BooleanField(default=False, verbose_name='Importado'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_shipping_required',
            field=models.BooleanField(default=False, verbose_name='Requiere envio'),
        ),
        migrations.AlterField(
            model_name='article',
            name='item_type',
            field=models.CharField(blank=True, max_length=144, verbose_name='Tipo de articulo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='line',
            field=models.CharField(blank=True, max_length=144, verbose_name='Linea'),
        ),
        migrations.AlterField(
            model_name='article',
            name='model',
            field=models.CharField(blank=True, max_length=144, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, max_length=144, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='origin',
            field=models.CharField(blank=True, max_length=144, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.ventas.models.get_upload_path, verbose_name='Foto de articulo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='price_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True, verbose_name='Precio 1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='price_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True, verbose_name='Precio 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='price_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True, verbose_name='Precio 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='price_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True, verbose_name='Precio 4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='price_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True, verbose_name='Precio 5'),
        ),
        migrations.AlterField(
            model_name='article',
            name='provider',
            field=models.CharField(blank=True, max_length=144, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ref',
            field=models.CharField(blank=True, max_length=144, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sales_unit',
            field=models.CharField(blank=True, max_length=144, verbose_name='Unidad de ventas'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL "SEO"'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.IntegerField(blank=True, default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sub_line',
            field=models.CharField(blank=True, max_length=144, verbose_name='Sublinea'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima actualización'),
        ),
        migrations.AlterField(
            model_name='category',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.ventas.models.get_upload_path, verbose_name='Foto de fondo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, max_length=144, upload_to='', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=144, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Category', verbose_name='Categoría padre'),
        ),
        migrations.AlterField(
            model_name='color',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(blank=True, max_length=9, verbose_name='Código Hexadecimal'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, max_length=144, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='department',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.ventas.models.get_upload_path, verbose_name='Foto de fondo'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='department',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.ventas.models.get_upload_path, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=144, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.CharField(blank=True, max_length=144, verbose_name='Slug "SEO"'),
        ),
        migrations.AlterField(
            model_name='line',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='line',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.ventas.models.get_upload_path, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(blank=True, max_length=144, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(blank=True, upload_to=src.ventas.models.get_upload_path, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.ventas.models.get_upload_path, verbose_name='Foto de fondo'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.ventas.models.get_upload_path, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.ventas.models.get_upload_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(blank=True, max_length=144, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='website',
            field=models.CharField(blank=True, max_length=144, verbose_name='Dirección url'),
        ),
        migrations.AlterField(
            model_name='subline',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='subline',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.ventas.models.get_upload_path, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='subline',
            name='name',
            field=models.CharField(blank=True, max_length=144, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='subline',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Line', verbose_name='Linea padre'),
        ),
        migrations.AlterField(
            model_name='type',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.ventas.models.get_upload_path, verbose_name='Foto de fondo'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='type',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=src.ventas.models.get_upload_path, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(blank=True, max_length=144, verbose_name='Nombre'),
        ),
    ]
